DROP TABLE users;
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR2(100),
    password VARCHAR2(150),
    active NUMBER(1)
);

DROP TABLE tasks;
CREATE TABLE tasks (
    task_id NUMBER GENERATED  BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    task_name VARCHAR2(100),
    complexity VARCHAR(20),
    description VARCHAR2(300),
    status VARCHAR2(20),
    start_date DATE,
    end_data DATE,
    CONSTRAINT fk_user_task FOREIGN KEY(user_id) REFERENCES users(user_id)
);